# Generated by Django 3.2.8 on 2024-06-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla9',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('N9', models.CharField(max_length=100, verbose_name='N°')),
                ('Descripcion9', models.TextField(null=True, verbose_name='Descripción')),
            ],
        ),
    ]
