# Generated by Django 3.2.8 on 2024-06-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla9',
            name='N9',
            field=models.IntegerField(verbose_name='N°'),
        ),
    ]
