# Generated by Django 3.2.8 on 2024-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0002_alter_tabla9_n9'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabla10',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('N10', models.CharField(default='', max_length=100, verbose_name='N°')),
                ('Descripcion10', models.TextField(null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.AlterField(
            model_name='tabla9',
            name='N9',
            field=models.CharField(default='', max_length=100, verbose_name='N°'),
        ),
    ]
