# Generated by Django 3.2.8 on 2024-05-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla9',
            name='Descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
