# Generated by Django 3.2.8 on 2024-05-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_tabla9_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla9',
            name='Descripcion',
        ),
        migrations.AddField(
            model_name='tabla9',
            name='Descripciones',
            field=models.TextField(null=True, verbose_name='Descripciones'),
        ),
    ]
