# Generated by Django 3.2.8 on 2024-05-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_auto_20240516_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla9',
            name='Descripciones',
        ),
        migrations.AddField(
            model_name='tabla9',
            name='Descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
