# Generated by Django 3.2.8 on 2024-05-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_auto_20240516_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla9',
            name='numero',
            field=models.CharField(default='Código', max_length=100, verbose_name='numero'),
        ),
        migrations.AlterField(
            model_name='tabla9',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
