# Generated by Django 3.2.8 on 2024-05-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_auto_20240516_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tabla9',
            new_name='tablaNueve',
        ),
    ]
