# Generated by Django 3.2.8 on 2024-05-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_rename_tabla9_tablanueve'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tablaNueve',
            new_name='tabla9',
        ),
    ]
