# Generated by Django 3.2.8 on 2024-05-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_rename_descripcion_tabla9_descripcions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabla9',
            old_name='Descripcions',
            new_name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='tabla9',
            name='numero',
        ),
        migrations.AddField(
            model_name='tabla9',
            name='N',
            field=models.CharField(default='Código', max_length=100, verbose_name='N'),
        ),
    ]
