# Generated by Django 3.2.8 on 2024-06-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_auto_20240602_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla10',
            name='Num',
        ),
    ]
