# Generated by Django 3.2.8 on 2024-06-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_remove_tabla10_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla10',
            name='num',
            field=models.CharField(default=' ', max_length=100, verbose_name='N'),
        ),
    ]
