# Generated by Django 3.2.8 on 2024-06-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0012_tabla10_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla10',
            name='num',
            field=models.IntegerField(default=0, verbose_name='N'),
        ),
    ]
