# Generated by Django 3.2.8 on 2024-06-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_alter_tabla10_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla9',
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='tabla9',
            name='N',
        ),
        migrations.AddField(
            model_name='tabla9',
            name='Descripcion9',
            field=models.TextField(null=True, verbose_name='Desc'),
        ),
        migrations.AddField(
            model_name='tabla9',
            name='N9',
            field=models.CharField(default=0, max_length=100, verbose_name='num'),
        ),
    ]
