# Generated by Django 3.2.8 on 2024-06-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_auto_20240604_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla9',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tabla9',
            name='numero',
        ),
        migrations.AddField(
            model_name='tabla9',
            name='Descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='tabla9',
            name='N',
            field=models.CharField(default=' ', max_length=100, verbose_name='N'),
        ),
    ]
