# Generated by Django 3.2.8 on 2024-06-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_auto_20240604_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabla9',
            old_name='Descripcion',
            new_name='Descripcion9',
        ),
        migrations.RenameField(
            model_name='tabla9',
            old_name='N',
            new_name='N9',
        ),
    ]
