# Generated by Django 3.2.8 on 2024-06-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_auto_20240605_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla10',
            name='num',
            field=models.IntegerField(default='', verbose_name='N'),
        ),
        migrations.AlterField(
            model_name='tabla9',
            name='N9',
            field=models.IntegerField(default='', verbose_name='N'),
        ),
    ]
